# http://docs.travis-ci.com/user/languages/r/
language: r

cache:
  packages: true

r:
  - release
  - devel

addons:
  apt:
    packages:
      - libgdal-dev
      - libudunits2-dev

r_packages:
  sf

after_success:
  - Rscript -e 'covr::coveralls(function_exclusions = c("\\.onLoad"))'

notifications:
  email:
  - zozlak@zozlak.org
#  - sebastian.boeck@boku.ac.at
